### ISSUE TITLE
Less nested structures

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#19]
In order to make it easier for developers that don't know YAML and might not be aware of its syntax I feel we could win a lot by using as many top level keys as possible.

```YAML
# this file is used to identify public code projects
# Read more at github.com/publiccode/publiccode.yml
version: 0.0.1                                        # publiccode YAML standard version 0.0.1

# Legal
authors-file: AUTHORS                                 # file listing copyright information
license: AGPL-3.0-or-later                            # SPDX expression of license

# Description
name: Medusa                                          # Short descriptive name
logo: img/logo.jpg                                    # Logo
shortDescription: A really interesting software.      # Max 100 characters
longDescription: >
  Very long description of this software, also split
  on multiple rows. You should note what the software
  is and why one should need it.
screenshots:                                          # Screen shots used to get a quick look&feel of the software
  - img/sshot1.jpg
  - img/sshot2.jpg
  - img/sshot3.jpg
videos:                                               # Demo videos of the software
  - https://youtube.com/xxxxxxxx 
stableVersion: "1.0"                                  # Last stable version
releaseDate: 2017-04-15                               # Date of last stable software release 
platforms: web                                        # or Windows, Mac, Linux, etc. 
```
