### ISSUE TITLE
Should `description` be multilingual?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/publiccode.yml#5]
Perhaps we should even mandate English as a required language, or as a default to fall back to?

**Comment by bvhme** [comment]
For example, with ISO 639-2 codes (I don't know if this is a good choice as a standard)

```yaml
description:
  name: Medusa                                          # Short descriptive name
  logo: img/logo.jpg                                    # Logo
  shortdesc: A really interesting software.             # Max 100 characters
  longdesc: >
    Very long description of this software, also split
    on multiple rows. You should note what the software
    is and why one should need it.
  screenshots:                                          # Screen shots used to get a quick look&feel of the software
    - img/sshot1.jpg
    - img/sshot2.jpg
    - img/sshot3.jpg
  videos:                                               # Demo videos of the software
    - https://youtube.com/xxxxxxxx
  translations:
    language: ita # Add any ISO 639-2 code to add a language
    shortdesc: A really interesting software.             # Max 100 characters
    longdesc: >
      Very long description of this software, also split
      on multiple rows. You should note what the software
      is and why one should need it.
    videos:                                               # Demo videos of the software
      - https://youtube.com/xxxxxxxx
```
